<?php

/**
 * PluginPostalCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPostalCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPostalCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPostalCode');
    }
}